-- 지정 시간에 쿼리 실행
WAITFOR TIME '22:10:00'
SELECT 'TIME'

-- 딜레이 쿼리 실행 5초뒤
WAITFOR DELAY '00:00:05'
SELECT 'DELAY'

-- 1번 세션
BEGIN TRAN
SET LOCK_TIMEOUT 3000
SELECT * FROM WORD_DIC WITH(UPDLOCK, ROWLOCK) WHERE WORD_ID = '8175'

COMMIT
ROLLBACK

-- 2번 세션, 1번 세션 COMMIT / ROLLBACK 전까지 대기 
BEGIN TRAN
SET LOCK_TIMEOUT 3000
SELECT * FROM WORD_DIC WITH(UPDLOCK, ROWLOCK) WHERE WORD_ID = '8175'

COMMIT
ROLLBACK